# Generated by Django 3.1.7 on 2022-07-02 00:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPasang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pasang', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Baru', 'Baru'), ('Proses', 'Proses'), ('Selesai', 'Selesai')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tanggal_pasang', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Detail Pasang',
            },
        ),
        migrations.AlterModelOptions(
            name='pelanggan',
            options={'verbose_name_plural': 'Pelanggan'},
        ),
        migrations.CreateModel(
            name='SettingPembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(max_length=200, null=True)),
                ('va', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Baru', 'Baru'), ('Lunas', 'Lunas')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('detailpasang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.detailpasang')),
                ('tahun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.tahun')),
            ],
            options={
                'verbose_name_plural': 'Setting Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Perbaikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Baru', 'Baru'), ('Proses', 'Proses'), ('Selesai', 'Selesai')], max_length=200, null=True)),
                ('keluhan', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('pelanggan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.pelanggan')),
            ],
            options={
                'verbose_name_plural': 'Perbaikan',
            },
        ),
        migrations.AddField(
            model_name='detailpasang',
            name='pelanggan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.pelanggan'),
        ),
        migrations.AddField(
            model_name='detailpasang',
            name='produk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.produk'),
        ),
    ]
