# Generated by Django 3.1.7 on 2022-07-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20220702_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tahun',
            old_name='tahun',
            new_name='nama',
        ),
    ]
