# Generated by Django 3.1.7 on 2022-07-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20220702_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='kalimat',
        ),
    ]
