# Generated by Django 3.1.7 on 2022-07-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_slide_kalimat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingpembayaran',
            name='status',
            field=models.CharField(choices=[('Baru', 'Baru'), ('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas')], max_length=200, null=True),
        ),
    ]
