# Generated by Django 3.1.7 on 2022-07-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20220702_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
