# Generated by Django 3.1.7 on 2022-07-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_produk_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpasang',
            name='keterangan',
            field=models.CharField(choices=[('Baru', 'Baru'), ('Proses', 'Proses'), ('Selesai', 'Selesai')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detailpasang',
            name='va',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
