# Generated by Django 3.1.7 on 2022-07-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20220703_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpasang',
            name='bank',
            field=models.CharField(choices=[('bri', 'bri'), ('bni', 'bni'), ('bca', 'bca')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasang',
            name='keterangan',
            field=models.CharField(choices=[('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas')], max_length=200, null=True),
        ),
    ]
