# Generated by Django 3.1.7 on 2022-07-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20220703_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpasang',
            name='keterangan',
            field=models.CharField(choices=[('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas'), ('Pembayaran Melebihi Batas Transaksi', 'Pembayaran Melebihi Batas Transaksi'), ('Anda Batalkan', 'Anda Batalkan'), ('Pembayaran Ditolak', 'Pembayaran Ditolak')], max_length=200, null=True),
        ),
    ]
