# Generated by Django 3.1.7 on 2022-07-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20220703_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpasang',
            name='va',
        ),
        migrations.AlterField(
            model_name='detailpasang',
            name='keterangan',
            field=models.CharField(choices=[('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas'), ('Kadaluarsa', 'Kadaluarsa'), ('Anda Batalkan', 'Anda Batalkan'), ('Pembayaran Ditolak', 'Pembayaran Ditolak')], max_length=200, null=True),
        ),
    ]
