# Generated by Django 3.1.7 on 2022-07-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_auto_20220703_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpasang',
            name='id_transaksi_va',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasang',
            name='bank',
            field=models.CharField(blank=True, choices=[('bri', 'bri'), ('bni', 'bni'), ('bca', 'bca')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasang',
            name='keterangan',
            field=models.CharField(blank=True, choices=[('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas'), ('Kadaluarsa', 'Kadaluarsa'), ('Anda Batalkan', 'Anda Batalkan'), ('Pembayaran Ditolak', 'Pembayaran Ditolak')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasang',
            name='kode_pasang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detailpasang',
            name='status',
            field=models.CharField(blank=True, choices=[('Baru', 'Baru'), ('Proses', 'Proses'), ('Selesai', 'Selesai')], max_length=200, null=True),
        ),
    ]
