# Generated by Django 3.1.7 on 2022-07-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_auto_20220703_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingpembayaran',
            name='id_transaksi_va',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='settingpembayaran',
            name='tahun',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
