# Generated by Django 3.1.7 on 2022-07-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_auto_20220704_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingpembayaran',
            name='va',
        ),
    ]
